version: '3.8'

services:
  postgres:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - ./testdata/certs:/tmp/certs:ro
      - ./testdata/custom_pg_hba.conf:/tmp/custom_pg_hba.conf:ro
      - ./testdata/docker-entrypoint.sh:/docker-entrypoint.sh:ro
      - ./testdata/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh:ro
    ports:
      - "5432:5432"
    entrypoint: ["/docker-entrypoint.sh"]


  dbp:
    build:
      context: .
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./testdata/certs:/certs:ro
      - ./testdata/env/pg/patches:/patches:ro
    command: >
      sh -c "
      until nc -z ${DB_HOST} ${DB_PORT}; do
        echo 'Waiting for Postgres...'
        sleep 2;
      done;
      dbp apply -e postgres --db.host ${DB_HOST} --db.port ${DB_PORT} --db.username ${DB_USER} --db.password ${DB_PASSWORD} --db.name ${DB_NAME} --db.sslrootcert ${DB_ROOTCERT} --db.sslmode  verify-full -f /patches -v
      "
