name: Build and Push Docker image

on:
  push:
    branches:
      - main  # or any other branch you want to trigger the workflow

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Fetch all history for all tags

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y make

    - name: Get Docker image tag
      id: get_tag
      run: echo "TAG=$(make versiontag)" >> $GITHUB_ENV

    - name: Build for amd64
      run: make build/$(PROG)-amd64

    - name: Build for arm64
      run: make build/$(PROG)-arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true

    - name: Create Buildx builder
      run: |
        docker buildx create --name mybuilder --use
        docker buildx inspect --bootstrap

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .  # Ensure the context is set to the project root
        file: ./Dockerfile  # Explicitly specify the Dockerfile location
        push: true
        no-cache: true  # Disable build cache
        platforms: linux/amd64,linux/arm64  # Specify target platforms
        tags: |
          livewireholdings/dbp:latest
          livewireholdings/dbp:${{ env.TAG }}

    - name: Logout from Docker Hub
      run: docker logout

